FROM ubuntu:24.04 AS builder

# Install dependencies for Rust development
RUN apt-get update && apt-get install -y \
  build-essential \
  pkg-config \
  libssl-dev \
  jq \
  curl \
  unzip \
  git \
  wget \
  clang \
  cmake \
  && apt-get clean

# Install Rust compiler (using rustup)
RUN useradd -ms /bin/bash runner && mkdir -p /home/runner/.cargo /home/runner/.rustup home/runner/work && chown -R runner:runner /home/runner

USER runner
ENV HOME=/home/runner \
    CARGO_HOME=/home/runner/.cargo \
    RUSTUP_HOME=/home/runner/.rustup \
    PATH=/home/runner/.cargo/bin:$PATH

# Install Rust 1.88.0
RUN curl -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain 1.88.0

ENV CARGO_HOME="/home/runner/.cargo"
ENV RUSTUP_HOME="/home/runner/.rustup"
ENV PATH="/home/runner/.cargo/bin:$PATH"

WORKDIR /home/runner/work/bdk-flutter/
# Copy the folder from root
COPY --chown=runner:runner src/ .
# Change directory
RUN chown -R runner:runner /home/runner/work/bdk-flutter
WORKDIR /home/runner/work/bdk-flutter/bdk-flutter/rust/

RUN mkdir -p ~/lib/linux

RUN mkdir -p  ~/release/linux

RUN cargo clean
RUN rustup target add x86_64-unknown-linux-gnu
RUN cargo build --release --target x86_64-unknown-linux-gnu

RUN mkdir -p ~/release/output_binaries
ENV SOURCE_DIR="/home/runner/work/bdk-flutter/bdk-flutter/rust/target/x86_64-unknown-linux-gnu/release/"
ENV DEST_DIR="/home/runner/release/output_binaries"

RUN find "$SOURCE_DIR" -maxdepth 1 -type f -name "*.so" -exec cp {} "$DEST_DIR" \; -quit

FROM ubuntu:22.04 AS final
RUN mkdir -p ~/release/output_binaries
COPY --from=builder /home/runner/release/output_binaries/*.so /root/release/output_binaries
WORKDIR /root/release/output_binaries

RUN ls

# Run a tiny program to make the build runnable
CMD ["sleep", "infinity"]